package com.notification.app.data.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.tasks.await

/**
 * Handles real Google Sign-In using the official Android Credential Manager API,
 * then exchanges the Google ID token for a Firebase Auth session.
 *
 * REQUIRED SETUP (see README.md):
 * 1. Create a Firebase project and add this app to it (package: com.notification.app)
 * 2. Download google-services.json into the /app folder
 * 3. In Firebase Console > Authentication > Sign-in method, enable "Google"
 * 4. Copy the "Web client ID" (Client type: Web application) generated by Firebase
 *    into WEB_CLIENT_ID below, or pass it via BuildConfig/.env
 *
 * Without a valid Web Client ID, sign-in will fail with a clear error — it will
 * NOT silently fall back to a fake/demo account.
 */
class GoogleAuthManager(private val context: Context) {

    // TODO: Replace with your Firebase project's real Web Client ID
    // (Firebase Console > Project Settings > General > Your Apps > Web client ID,
    // or the "client_type: 3" entry inside your google-services.json)
    private val webClientId: String = com.notification.app.BuildConfig.GOOGLE_WEB_CLIENT_ID

    private val firebaseAuth: FirebaseAuth by lazy { FirebaseAuth.getInstance() }

    sealed class AuthResult {
        data class Success(val name: String, val email: String) : AuthResult()
        data class Failure(val message: String) : AuthResult()
    }

    /**
     * Launches the real Google account picker and signs the user into Firebase.
     * Must be called from a Composable with access to an Activity context.
     */
    suspend fun signIn(): AuthResult {
        if (webClientId.isBlank() || webClientId.contains("REPLACE_ME")) {
            return AuthResult.Failure(
                "Google Sign-In is not configured yet. Add your Firebase Web Client ID " +
                    "to local.properties as GOOGLE_WEB_CLIENT_ID=... and rebuild the app."
            )
        }

        return try {
            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(webClientId)
                .setAutoSelectEnabled(false)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val credentialManager = CredentialManager.create(context)
            val response = credentialManager.getCredential(context, request)

            val credential = response.credential
            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken

                val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = firebaseAuth.signInWithCredential(firebaseCredential).await()

                val user = authResult.user
                if (user != null) {
                    AuthResult.Success(
                        name = user.displayName ?: googleIdTokenCredential.displayName ?: "User",
                        email = user.email ?: googleIdTokenCredential.id
                    )
                } else {
                    AuthResult.Failure("Firebase sign-in returned no user.")
                }
            } else {
                AuthResult.Failure("Unexpected credential type returned by Credential Manager.")
            }
        } catch (e: androidx.credentials.exceptions.NoCredentialException) {
            // Most common causes: the app's signing certificate SHA-1 is not
            // registered in Firebase (Project settings → Add fingerprint),
            // or no Google account exists on the device.
            AuthResult.Failure(
                "تعذر العثور على حساب جوجل صالح — تأكد من وجود حساب جوجل على الجهاز، " +
                    "وأن بصمة توقيع التطبيق (SHA-1) مضافة في إعدادات Firebase.\n" +
                    "No valid Google credentials — make sure a Google account exists on this " +
                    "device and the app's SHA-1 fingerprint is registered in Firebase."
            )
        } catch (e: GetCredentialException) {
            AuthResult.Failure(e.message ?: "Sign-in was cancelled or failed.")
        } catch (e: GoogleIdTokenParsingException) {
            AuthResult.Failure("Failed to parse Google ID token: ${e.message}")
        } catch (e: Exception) {
            AuthResult.Failure(e.message ?: "Unknown sign-in error.")
        }
    }

    fun signOut() {
        firebaseAuth.signOut()
    }

    fun currentUserId(): String? = firebaseAuth.currentUser?.uid
}
